In [1]:
!pip install kagglehub

Requirement already satisfied: kagglehub in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.0.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (0.1.23)
Requirement already satisfied: packaging in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (26.2)
Requirement already satisfied: pyyaml in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kagglehub) (2026.4.22)
Requirement already satisfied: colorama in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kagglehub

# Download latest version
df = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", df)

C:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [3]:
import pandas as pd

In [4]:
import os

# Check current working directory
print("Current directory:", os.getcwd())

# List everything in current folder
print("\nFiles here:")
for f in os.listdir():
    print(f)

Current directory: C:\Users\dell

Files here:
.anaconda
.cache
.conda
.condarc
.continuum
.ipynb_checkpoints
.ipython
.jupyter
.matplotlib
.python_history
.spss
3D Objects
AppData
Application Data
battery-report.html
Contacts
Cookies
data
Documents
Downloads
edb_mtk.exe
edb_npgsql.exe
edb_pgagent_pg18.exe
edb_pgjdbc.exe
edb_psqlodbc.exe
Favorites
IntelGraphicsProfiles
LingvanexTranslator
Links
Local Settings
logs
Microsoft
miniconda3
Music
My Documents
NetHood
NTUSER.DAT
ntuser.dat.LOG1
ntuser.dat.LOG2
NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf
NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms
NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms
ntuser.ini
OneDrive
pemhttpd.exe
postgis_3_6_pg18.exe
postgresql_13.exe
PrintHood
python.cleaningecommerce
Recent
Saved Games
Searches
SendTo
Start Menu
Templates
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
Videos
visuals

In [5]:
# Search for the olist CSV files anywhere on your system
import os

for root, dirs, files in os.walk("C:/Users"):
    for file in files:
        if "olist" in file.lower():
            print(os.path.join(root, file))

C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_customers_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_geolocation_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_orders_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_items_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_payments_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_reviews_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_products_dataset.csv
C:/Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_sellers_dataset.csv
C:/Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\tests\series\methods\test_tolist.py
C:/Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\tests\series\methods\__pycache__\test_tolist.cpython-313.pyc

In [6]:
import kagglehub
import os

path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")
print(" Dataset path:", path)
print("\nFiles available:")
for f in os.listdir(path):
    print(f)

 Dataset path: C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

Files available:
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

path = r"C:\Users\dell\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2" + "\\"

orders = pd.read_csv(path + "olist_orders_dataset.csv")
payments = pd.read_csv(path + "olist_order_payments_dataset.csv")
order_items = pd.read_csv(path + "olist_order_items_dataset.csv")
products = pd.read_csv(path + "olist_products_dataset.csv")
customers = pd.read_csv(path + "olist_customers_dataset.csv")
sellers = pd.read_csv(path + "olist_sellers_dataset.csv")
reviews = pd.read_csv(path + "olist_order_reviews_dataset.csv")
category_translation = pd.read_csv(path + "product_category_name_translation.csv")

print("✅ All files loaded!")
print(f"Orders        : {orders.shape}")
print(f"Payments      : {payments.shape}")
print(f"Order Items   : {order_items.shape}")
print(f"Products      : {products.shape}")
print(f"Customers     : {customers.shape}")
print(f"Sellers       : {sellers.shape}")
print(f"Reviews       : {reviews.shape}")

✅ All files loaded!
Orders        : (99441, 8)
Payments      : (103886, 5)
Order Items   : (112650, 7)
Products      : (32951, 9)
Customers     : (99441, 5)
Sellers       : (3095, 4)
Reviews       : (99224, 7)

In [8]:
for name, df in {"Orders": orders, "Payments": payments,
                  "Order Items": order_items, "Products": products,
                  "Customers": customers}.items():
    print(f"\n{'='*45}")
    print(f" {name} | Shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if len(nulls) > 0:
        print(f"Nulls:\n{nulls}")
    else:
        print("Nulls: None ✅")

=============================================
 Orders | Shape: (99441, 8)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Nulls:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

=============================================
 Payments | Shape: (103886, 5)
Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
Nulls: None ✅

=============================================
 Order Items | Shape: (112650, 7)
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
Nulls: None ✅

=============================================
 Products | Shape: (32951, 9)
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
Nulls:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

=============================================
 Customers | Shape: (99441, 5)
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Nulls: None ✅

In [9]:
# Parse dates
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

# Keep only delivered orders
orders = orders[orders['order_status'] == 'delivered']
orders.dropna(subset=['order_delivered_customer_date'], inplace=True)

print(f"✅ Orders cleaned: {orders.shape[0]} delivered orders")

✅ Orders cleaned: 96470 delivered orders

In [10]:
# Translate categories to English
products = products.merge(category_translation, on='product_category_name', how='left')
products['product_category_name_english'].fillna('unknown', inplace=True)
products.drop(columns=['product_category_name', 'product_name_lenght',
                        'product_description_lenght', 'product_photos_qty'],
              inplace=True, errors='ignore')

print(f"✅ Products cleaned: {products.shape}")
print(products[['product_id','product_category_name_english']].head(3))

✅ Products cleaned: (32951, 6)
                         product_id product_category_name_english
0  1e9e8ef04dbcff4541ed26657ea517e5                     perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f                           art
2  96bd76ec8810374ed1b65e291975717f                sports_leisure

In [11]:
print("All columns in df:")
print(list(df.columns))

All columns in df:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [12]:
# Reload orders fresh
orders = pd.read_csv(path + "olist_orders_dataset.csv")

# Parse dates BEFORE merging
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

# Filter delivered only
orders = orders[orders['order_status'] == 'delivered']
orders.dropna(subset=['order_delivered_customer_date'], inplace=True)

print(f"✅ Orders ready: {orders.shape}")
print("Columns:", list(orders.columns))

✅ Orders ready: (96470, 8)
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [13]:
orders.count()

order_id                         96470
customer_id                      96470
order_status                     96470
order_purchase_timestamp         96470
order_approved_at                96456
order_delivered_carrier_date     96469
order_delivered_customer_date    96470
order_estimated_delivery_date    96470
dtype: int64

In [14]:
orders.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      1
order_delivered_customer_date     0
order_estimated_delivery_date     0
dtype: int64

In [15]:
# Remove cancelled/unavailable orders, keep only delivered
orders = orders[orders['order_status'] == 'delivered']
print("Delivered orders:", len(orders))

Delivered orders: 96470

In [16]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
print("✅ Date fixed!")
orders.dtypes

✅ Date fixed!

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [17]:
import os
os.makedirs("data/processed", exist_ok=True)
orders.to_csv("data/processed/orders_clean.csv", index=False)
print("✅ Saved!")

✅ Saved!

In [18]:
payments.head

<bound method NDFrame.head of                                 order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
...                                  ...                 ...          ...
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
0                          8          99.33
1                          1          24.39
2                          1          65.71
3                          8         107.78
4                          2         128.45
...                      ...            ...
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58

[103886 rows x 5 columns]>

In [19]:
payments.describe

<bound method NDFrame.describe of                                 order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
...                                  ...                 ...          ...
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
0                          8          99.33
1                          1          24.39
2                          1          65.71
3                          8         107.78
4                          2         128.45
...                      ...            ...
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58

[103886 rows x 5 columns]>

In [20]:
payments.info

<bound method DataFrame.info of                                 order_id  payment_sequential payment_type  \
0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
...                                  ...                 ...          ...
103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

        payment_installments  payment_value
0                          8          99.33
1                          1          24.39
2                          1          65.71
3                          8         107.78
4                          2         128.45
...                      ...            ...
103881                     1         363.31
103882                     2          96.80
103883                     1          47.77
103884                     5         369.54
103885                     1         191.58

[103886 rows x 5 columns]>

In [21]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [22]:
payments.to_csv("data/processed/payments_clean.csv", index=False)
print("✅ Payments saved!")

✅ Payments saved!

In [23]:
products = pd.read_csv(path + "olist_products_dataset.csv")
print("Shape:", products.shape)
products.head()

Shape: (32951, 9)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [24]:
customers.to_csv("data/processed/customers_clean.csv", index=False)
print("✅ Customers saved!")

✅ Customers saved!

In [25]:
order_items = pd.read_csv(path + "olist_order_items_dataset.csv")
print("Shape:", order_items.shape)
order_items.head()

Shape: (112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [26]:
import os

files = os.listdir("data/processed")
print("✅ Files saved:")
for f in files:
    print(" -", f)

✅ Files saved:
 - .ipynb_checkpoints
 - customers_clean.csv
 - master_data.csv
 - orders_clean.csv
 - order_items_clean.csv
 - payments_clean.csv
 - products_clean.csv
 - sellers_clean.csv
 - Untitled.ipynb

In [27]:
import os
print(os.getcwd())

C:\Users\dell

In [28]:
import shutil
import os

# Create public folder
os.makedirs(r"C:\tmp", exist_ok=True)

# Copy all clean files there
files = ['orders_clean.csv', 'payments_clean.csv', 'customers_clean.csv',
         'products_clean.csv', 'order_items_clean.csv', 'sellers_clean.csv']

for f in files:
    shutil.copy(f"data/processed/{f}", f"C:\\tmp\\{f}")
    print(f"✅ Copied {f}")

print("\n✅ All files copied to C:\\tmp\\")

✅ Copied orders_clean.csv
✅ Copied payments_clean.csv
✅ Copied customers_clean.csv
✅ Copied products_clean.csv
✅ Copied order_items_clean.csv
✅ Copied sellers_clean.csv

✅ All files copied to C:\tmp\

In [30]:
products = pd.read_csv(r"C:\tmp\products_clean.csv")
print(products.columns.tolist())
print(products.shape)
products.head(2)

['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'product_category_name_english']
(32951, 10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art